### ISSUE TITLE
Unnamed LootPool strikes back

### ISSUE THREAD

**Issue by Aizistral** [Shoxie12/MCDJ#13]
Basically, this line of code:

https://github.com/Shoxie12/MCDJ/blob/5800473e11fe3dcd2a4f0bc8722d17795f24b4c0/src/main/java/com/shoxie/mcdj/EventsHandler.java#L32

You should always name `LootPool`s you inject by calling `LootPool.Builder#name(String)`. Set it to whatever, just make sure that whatever is not `null`. Otherwise you will cause an error state if any other mod attempts to inject to the same table, which in turn leads to no loot being generated from affected loot table.

For reference and some more info, you can take a look at this: https://github.com/Extegral/Enigmatic-Legacy/issues/132

**Comment by MokahTGS** [comment]
Yup, please fix, getting this issue with the current versions.

**Comment by Shoxie12** [comment]
Thanks for the tip. Fixed in 2.1.1

**Comment by Aizistral** [comment]
Great.
