### ISSUE TITLE
Music keeps playing at full Volume

### ISSUE THREAD

**Issue by NightBloodSteel** [Shoxie12/MCDJ#14]
Music keeps playing at full Volume as you get further away from the Jukebox.
Doesn't happen with the original music disks from Minecraft, only with the MCDJ ones.

Happens on MC 1.16.5 with Forge 36.0.14, in Singleplayer and Multiplayer.
MCDJ was the only mod Loaded.

**Comment by Shoxie12** [comment]
To solve this problem please convert all you music to mono, not stereo.

I have added wiki corrections describing this issue:
https://github.com/Shoxie12/MCDJ/wiki/Preparing-and-adding-your-music-to-the-game#1-converting-your-music-to-ogg-vorbis-format
