### ISSUE TITLE
Biomes get change on the server

### ISSUE THREAD

**Issue by SyrusWhite** [Shoxie12/MCDJ#17]
After installing MCDJ mod for Minecraft 1.16.5 on Forge 36.1.0 everything seems fine. It when I go to make and put an .OGG music file folder and boot up Minecraft for my server that issues begin. I followed your instructions on converting a MP3 to a .OGG using Audacity, which thank you. It was simple. I move the file to the streaming folder on my server as well as my client side. When I first attempted to log in I would get the synchronization error. Honestly I don't know how it fixed itself. I went into single player to see if it even worked at all and it did. No issue there. Then I attempted to log back in the server and boom, it worked. After logging in I realized something is off. I have a mod called Better end mod and one of the those biomes from the end was in the over world. As I traveled through out the overworld  all of the biomes were completely different. not all had the drastic effect of the " Shadow Forest" biome change but the biomes changed regardless. I uploaded the latest.log I have as well as the Debug.log. Not sure if they would be of assistance to you. I also attached an image of what it did to the world... lol The shadow Forest effect.
![Biome Changed](https://user-images.githubusercontent.com/82712207/117676926-9be89b00-b173-11eb-834c-fb35ef16115c.png)

[latest.log](https://github.com/Shoxie12/MCDJ/files/6452839/latest.log)
[debug.log](https://github.com/Shoxie12/MCDJ/files/6452840/debug.log)

**Comment by SyrusWhite** [comment]
This is an issue on Betterend.

**Comment by Shoxie12** [comment]
According to log files MCDJ loads fine. I can't see the possible mod conflicts... 
Please, can you try to remove all other mods and recreate world?

**Comment by SyrusWhite** [comment]
Yes, I did some more extensive digging to find out the issue and it happens to be on Betterends side. Its a minorbug I hope they plan to fix soon.
