### ISSUE TITLE
[feature request] toggle generation of shortcut file 

### ISSUE THREAD

**Issue by MBarnulf** [Shoxie12/MCDJ#2]
When using multiMC, the importation of instances including shortcuts generally fails, so to export an instance containing this mod, we have to delete /.minecraft/Music.lnk, but this file isn't "required" to make the mod work,

so if it was possible to add a configuration file with a parameter to prevent this file to generate when launching minecraft, that would be handy for modpack creators.

**Comment by Shoxie12** [comment]
Yes, it is possibe, I'll add  this feature in next update

**Comment by Shoxie12** [comment]
Added in v1.3
