### ISSUE TITLE
Everything's cool, until I realised that the music is still played at the same volume even if I am far away from the box

### ISSUE THREAD

**Issue by eimer-gamer** [Shoxie12/MCDJ#29]
Like, make the volume lower the futher you go from box?

**Comment by A1iex-69** [comment]
Try converting .ogg to the mono format, it might be stereo
stereo plays everythere

**Comment by Shoxie12** [comment]
[sa5ha42](https://github.com/sa5ha42) is correct. If you save ogg files in mono, it will plays same as vanilla records.
