### ISSUE TITLE
When server .ogg files don't match players get stuck at encrypting. 1.16.3 add a way to sync client to server.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Shoxie12/MCDJ#5]
So I run this modpack. https://www.technicpack.net/modpack/project-evolution-main-course.1765540 and it has a 50 slot server but when I used audacity to convert some mp3 files to ogg and I put them on the server this error occured when players who didn't have the exact ogg files had. https://gist.github.com/P3rf3ctXZer0/4f119cd460e5a10901d2e8e41bc6fcaa it seems that for some reason there is nothing in place to push server files to client - if possible could you create a way for clients to recieve .ogg files through 1mb packets only when people play the music? This would effectively always make sure clients and servers match. I have a lot of time and the ability to test things if you need me to.

At time of writing this - this is the changelog https://github.com/P3rf3ctXZer0/Project-Evolution-Main-Course/releases/tag/project-evolution-main-course-10.0.0

This is your mod version.
Audio Cassettes v1.0 for 1.16.3
MCDJ v2.0 for 1.16.3

**Comment by Shoxie12** [comment]
Theoretically it is possible to sync ogg files from server to client, but syncing music directly from minecraft server is probably dangerous thing. Previously i tried to make it possible but i face with a lot of bug. 
I will not give up on this idea, but for now i can only recommend you to use mods that can play internet radio or don't change playlist on the server so often.

**Comment by Peiprjs** [comment]
To @P3rf3ctXZer0, you could make use of Discord to transfer the music

**Comment by P3rf3ctXZer0** [comment]
You should speak with dev of Better Records - they figured out how to do it.
